# Generated by Django 5.0.4 on 2024-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_log',
            field=models.TextField(blank=True, max_length=99999, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='appointments',
            field=models.ManyToManyField(blank=True, null=True, to='main.appointment'),
        ),
    ]
