# Generated by Django 5.0.4 on 2024-04-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='user_profile',
        ),
    ]
